version: '3.8'

services:
  hivision_idphotos:
    build:
      context: .
      dockerfile: Dockerfile
    image: linzeyi/hivision_idphotos
    command: python3 -u app.py --host 0.0.0.0 --port 7860
    ports:
      - '7860:7860'

  hivision_idphotos_api:
    build:
      context: .
      dockerfile: Dockerfile
    image: linzeyi/hivision_idphotos
    command: python3 deploy_api.py
    ports:
      - '8080:8080'
